## ZCU111 bare-metal / DDR4 constraints.
## SD, Ethernet, RFDC, and DPTI are intentionally not constrained.

## CLK_100 fixed 100 MHz LVDS clock, U46 -> U1 bank 64.
## USER_SI570/J19/J18 is also available, but shares bank 69 with PMOD_1/J49.
set_property -dict {PACKAGE_PIN AM15 IOSTANDARD LVDS} [get_ports sys_clk_p]
set_property -dict {PACKAGE_PIN AN15 IOSTANDARD LVDS} [get_ports sys_clk_n]
create_clock -period 10.000 -name sys_clk_pin [get_ports sys_clk_p]

## PL DDR4 300 MHz USER_SI570 differential clock, U47 -> U1 bank 69.
## Electrical standards and the generated clock are supplied by the DDR4 IP XDC.
set_property PACKAGE_PIN J19 [get_ports c0_sys_clk_p]
set_property PACKAGE_PIN J18 [get_ports c0_sys_clk_n]

## PL DDR4 component memory, banks 67/68/69.
## Command/address. DDR4 WE/CAS/RAS pins are address bits A14/A15/A16.
set_property PACKAGE_PIN D18 [get_ports {c0_ddr4_adr[0]}]
set_property PACKAGE_PIN E19 [get_ports {c0_ddr4_adr[1]}]
set_property PACKAGE_PIN E17 [get_ports {c0_ddr4_adr[2]}]
set_property PACKAGE_PIN E18 [get_ports {c0_ddr4_adr[3]}]
set_property PACKAGE_PIN E16 [get_ports {c0_ddr4_adr[4]}]
set_property PACKAGE_PIN F16 [get_ports {c0_ddr4_adr[5]}]
set_property PACKAGE_PIN F19 [get_ports {c0_ddr4_adr[6]}]
set_property PACKAGE_PIN G19 [get_ports {c0_ddr4_adr[7]}]
set_property PACKAGE_PIN F15 [get_ports {c0_ddr4_adr[8]}]
set_property PACKAGE_PIN G15 [get_ports {c0_ddr4_adr[9]}]
set_property PACKAGE_PIN G18 [get_ports {c0_ddr4_adr[10]}]
set_property PACKAGE_PIN H18 [get_ports {c0_ddr4_adr[11]}]
set_property PACKAGE_PIN K17 [get_ports {c0_ddr4_adr[12]}]
set_property PACKAGE_PIN L17 [get_ports {c0_ddr4_adr[13]}]
set_property PACKAGE_PIN B17 [get_ports {c0_ddr4_adr[14]}]
set_property PACKAGE_PIN D15 [get_ports {c0_ddr4_adr[15]}]
set_property PACKAGE_PIN C18 [get_ports {c0_ddr4_adr[16]}]
set_property PACKAGE_PIN K18 [get_ports {c0_ddr4_ba[0]}]
set_property PACKAGE_PIN K19 [get_ports {c0_ddr4_ba[1]}]
set_property PACKAGE_PIN C16 [get_ports {c0_ddr4_bg[0]}]
set_property PACKAGE_PIN A16 [get_ports {c0_ddr4_cke[0]}]
set_property PACKAGE_PIN D16 [get_ports {c0_ddr4_cs_n[0]}]
set_property PACKAGE_PIN B19 [get_ports {c0_ddr4_odt[0]}]
set_property PACKAGE_PIN A19 [get_ports c0_ddr4_act_n]
set_property PACKAGE_PIN A17 [get_ports c0_ddr4_reset_n]
set_property PACKAGE_PIN G17 [get_ports {c0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN F17 [get_ports {c0_ddr4_ck_c[0]}]

## Data masks / DBI.
set_property PACKAGE_PIN G13 [get_ports {c0_ddr4_dm_dbi_n[0]}]
set_property PACKAGE_PIN C12 [get_ports {c0_ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN K13 [get_ports {c0_ddr4_dm_dbi_n[2]}]
set_property PACKAGE_PIN J8  [get_ports {c0_ddr4_dm_dbi_n[3]}]
set_property PACKAGE_PIN C23 [get_ports {c0_ddr4_dm_dbi_n[4]}]
set_property PACKAGE_PIN F21 [get_ports {c0_ddr4_dm_dbi_n[5]}]
set_property PACKAGE_PIN J23 [get_ports {c0_ddr4_dm_dbi_n[6]}]
set_property PACKAGE_PIN N20 [get_ports {c0_ddr4_dm_dbi_n[7]}]

## Data strobes.
set_property PACKAGE_PIN E13 [get_ports {c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN E12 [get_ports {c0_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN C15 [get_ports {c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN B15 [get_ports {c0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN J14 [get_ports {c0_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN J13 [get_ports {c0_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN H8  [get_ports {c0_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN G8  [get_ports {c0_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN B22 [get_ports {c0_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN A22 [get_ports {c0_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN D23 [get_ports {c0_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN D24 [get_ports {c0_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN J20 [get_ports {c0_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN H20 [get_ports {c0_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN K21 [get_ports {c0_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN K22 [get_ports {c0_ddr4_dqs_c[7]}]

## Data bus.
set_property PACKAGE_PIN D14 [get_ports {c0_ddr4_dq[0]}]
set_property PACKAGE_PIN E11 [get_ports {c0_ddr4_dq[1]}]
set_property PACKAGE_PIN F14 [get_ports {c0_ddr4_dq[2]}]
set_property PACKAGE_PIN F12 [get_ports {c0_ddr4_dq[3]}]
set_property PACKAGE_PIN E14 [get_ports {c0_ddr4_dq[4]}]
set_property PACKAGE_PIN H12 [get_ports {c0_ddr4_dq[5]}]
set_property PACKAGE_PIN G14 [get_ports {c0_ddr4_dq[6]}]
set_property PACKAGE_PIN H13 [get_ports {c0_ddr4_dq[7]}]
set_property PACKAGE_PIN B13 [get_ports {c0_ddr4_dq[8]}]
set_property PACKAGE_PIN A15 [get_ports {c0_ddr4_dq[9]}]
set_property PACKAGE_PIN A12 [get_ports {c0_ddr4_dq[10]}]
set_property PACKAGE_PIN A14 [get_ports {c0_ddr4_dq[11]}]
set_property PACKAGE_PIN D13 [get_ports {c0_ddr4_dq[12]}]
set_property PACKAGE_PIN B14 [get_ports {c0_ddr4_dq[13]}]
set_property PACKAGE_PIN A11 [get_ports {c0_ddr4_dq[14]}]
set_property PACKAGE_PIN C13 [get_ports {c0_ddr4_dq[15]}]
set_property PACKAGE_PIN K11 [get_ports {c0_ddr4_dq[16]}]
set_property PACKAGE_PIN J11 [get_ports {c0_ddr4_dq[17]}]
set_property PACKAGE_PIN H10 [get_ports {c0_ddr4_dq[18]}]
set_property PACKAGE_PIN F11 [get_ports {c0_ddr4_dq[19]}]
set_property PACKAGE_PIN K10 [get_ports {c0_ddr4_dq[20]}]
set_property PACKAGE_PIN F10 [get_ports {c0_ddr4_dq[21]}]
set_property PACKAGE_PIN J10 [get_ports {c0_ddr4_dq[22]}]
set_property PACKAGE_PIN H11 [get_ports {c0_ddr4_dq[23]}]
set_property PACKAGE_PIN G9  [get_ports {c0_ddr4_dq[24]}]
set_property PACKAGE_PIN G7  [get_ports {c0_ddr4_dq[25]}]
set_property PACKAGE_PIN F9  [get_ports {c0_ddr4_dq[26]}]
set_property PACKAGE_PIN G6  [get_ports {c0_ddr4_dq[27]}]
set_property PACKAGE_PIN H6  [get_ports {c0_ddr4_dq[28]}]
set_property PACKAGE_PIN H7  [get_ports {c0_ddr4_dq[29]}]
set_property PACKAGE_PIN J9  [get_ports {c0_ddr4_dq[30]}]
set_property PACKAGE_PIN K9  [get_ports {c0_ddr4_dq[31]}]
set_property PACKAGE_PIN C22 [get_ports {c0_ddr4_dq[32]}]
set_property PACKAGE_PIN A20 [get_ports {c0_ddr4_dq[33]}]
set_property PACKAGE_PIN A21 [get_ports {c0_ddr4_dq[34]}]
set_property PACKAGE_PIN C21 [get_ports {c0_ddr4_dq[35]}]
set_property PACKAGE_PIN A24 [get_ports {c0_ddr4_dq[36]}]
set_property PACKAGE_PIN B20 [get_ports {c0_ddr4_dq[37]}]
set_property PACKAGE_PIN B24 [get_ports {c0_ddr4_dq[38]}]
set_property PACKAGE_PIN C20 [get_ports {c0_ddr4_dq[39]}]
set_property PACKAGE_PIN E24 [get_ports {c0_ddr4_dq[40]}]
set_property PACKAGE_PIN E22 [get_ports {c0_ddr4_dq[41]}]
set_property PACKAGE_PIN E23 [get_ports {c0_ddr4_dq[42]}]
set_property PACKAGE_PIN G20 [get_ports {c0_ddr4_dq[43]}]
set_property PACKAGE_PIN F24 [get_ports {c0_ddr4_dq[44]}]
set_property PACKAGE_PIN E21 [get_ports {c0_ddr4_dq[45]}]
set_property PACKAGE_PIN F20 [get_ports {c0_ddr4_dq[46]}]
set_property PACKAGE_PIN D21 [get_ports {c0_ddr4_dq[47]}]
set_property PACKAGE_PIN H23 [get_ports {c0_ddr4_dq[48]}]
set_property PACKAGE_PIN G23 [get_ports {c0_ddr4_dq[49]}]
set_property PACKAGE_PIN K24 [get_ports {c0_ddr4_dq[50]}]
set_property PACKAGE_PIN G22 [get_ports {c0_ddr4_dq[51]}]
set_property PACKAGE_PIN J21 [get_ports {c0_ddr4_dq[52]}]
set_property PACKAGE_PIN H22 [get_ports {c0_ddr4_dq[53]}]
set_property PACKAGE_PIN L24 [get_ports {c0_ddr4_dq[54]}]
set_property PACKAGE_PIN H21 [get_ports {c0_ddr4_dq[55]}]
set_property PACKAGE_PIN L23 [get_ports {c0_ddr4_dq[56]}]
set_property PACKAGE_PIN L20 [get_ports {c0_ddr4_dq[57]}]
set_property PACKAGE_PIN L22 [get_ports {c0_ddr4_dq[58]}]
set_property PACKAGE_PIN L21 [get_ports {c0_ddr4_dq[59]}]
set_property PACKAGE_PIN M20 [get_ports {c0_ddr4_dq[60]}]
set_property PACKAGE_PIN L19 [get_ports {c0_ddr4_dq[61]}]
set_property PACKAGE_PIN M19 [get_ports {c0_ddr4_dq[62]}]
set_property PACKAGE_PIN N19 [get_ports {c0_ddr4_dq[63]}]

## CPU reset pushbutton, active high.
set_property -dict {PACKAGE_PIN AF15 IOSTANDARD LVCMOS18} [get_ports cpu_reset]
set_false_path -from [get_ports cpu_reset]

## X-HEEP programmer UART0 through ZCU111 PMOD_1/J49.
## Programmer TX0 -> FPGA RXD on PMOD1_4 / J49.2.
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS12} [get_ports rx]
## FPGA TXD -> programmer RX0 on PMOD1_0 / J49.1.
set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS12} [get_ports tx]

## User LEDs, active high.
set_property -dict {PACKAGE_PIN AR13 IOSTANDARD LVCMOS18} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN AP13 IOSTANDARD LVCMOS18} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN AR16 IOSTANDARD LVCMOS18} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN AP16 IOSTANDARD LVCMOS18} [get_ports {led[3]}]
set_property -dict {PACKAGE_PIN AP15 IOSTANDARD LVCMOS18} [get_ports {led[4]}]
set_property -dict {PACKAGE_PIN AN16 IOSTANDARD LVCMOS18} [get_ports {led[5]}]
set_property -dict {PACKAGE_PIN AN17 IOSTANDARD LVCMOS18} [get_ports {led[6]}]
set_property -dict {PACKAGE_PIN AV15 IOSTANDARD LVCMOS18} [get_ports {led[7]}]

## User DIP switches, active high.
set_property -dict {PACKAGE_PIN AF16 IOSTANDARD LVCMOS18} [get_ports {sw[0]}]
set_property -dict {PACKAGE_PIN AF17 IOSTANDARD LVCMOS18} [get_ports {sw[1]}]
set_property -dict {PACKAGE_PIN AH15 IOSTANDARD LVCMOS18} [get_ports {sw[2]}]
set_property -dict {PACKAGE_PIN AH16 IOSTANDARD LVCMOS18} [get_ports {sw[3]}]
set_property -dict {PACKAGE_PIN AH17 IOSTANDARD LVCMOS18} [get_ports {sw[4]}]
set_property -dict {PACKAGE_PIN AG17 IOSTANDARD LVCMOS18} [get_ports {sw[5]}]
set_property -dict {PACKAGE_PIN AJ15 IOSTANDARD LVCMOS18} [get_ports {sw[6]}]
set_property -dict {PACKAGE_PIN AJ16 IOSTANDARD LVCMOS18} [get_ports {sw[7]}]

## RISC-V debug JTAG through X-HEEP programmer PMOD_1 -> ZCU111 PMOD_1/J49.
## JTAG timing constraints are inherited from constraints/ariane.xdc.
## X-HEEP ADBUS0 TCK -> ZCU111 PMOD1_5 / J49.4.
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS12} [get_ports tck]
## PMOD TCK is not on a dedicated clock route; this matches other CVA6 PMOD JTAG boards.
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets tck_IBUF_inst/O]
## X-HEEP ADBUS3 TMS -> ZCU111 PMOD1_2 / J49.5.
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS12} [get_ports tms]
## X-HEEP ADBUS1 TDI -> ZCU111 PMOD1_1 / J49.3.
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS12} [get_ports tdi]
## ZCU111 PMOD1_6 / J49.6 -> X-HEEP ADBUS2 TDO.
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS12} [get_ports tdo]
